@startuml diagram-topology

' !define AzurePuml https://raw.githubusercontent.com/travisnielsen/Azure-PlantUML/themesupport/dist
!define AzurePuml https://raw.githubusercontent.com/travisnielsen/Azure-PlantUML/themesupport/dist

' Theme
' !includeurl AzurePuml/themes/blueprint.puml
' !includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/themes/dracula.puml

' C4
' !includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

!includeurl AzurePuml/Management/AzureSubscription.puml
!includeurl AzurePuml/Networking/AzureVirtualNetwork.puml
!includeurl AzurePuml/Networking/AzureDNS.puml
!includeurl AzurePuml/Networking/AzureVPNGateway.puml
!includeurl AzurePuml/Networking/AzureExpressRoute.puml

LAYOUT_LEFT_RIGHT

TITLE: Island Network Topology

skinparam Rectangle {
    BorderColor<<island>> GREEN
    BorderThickness<<island>> 6
}

skinparam rectangle<<e_stereo>> {
    BackgroundColor<<Region>> BACKGROUND
	BorderColor<<Region>> RED
	BackgroundColor<<AzureSubscription>> SELECTION
	BorderColor<<AzureSubscription>> YELLOW
    BackgroundColor<<AzureVirtualNetwork>> BACKGROUND
    BorderColor<<AzureVirtualNetwork>> ORANGE
    BackgroundColor<<AzureSubnet>> SELECTION
    BorderColor<<AzureSubnet>> ORANGE
    BorderColor<<AzureRouteTable>> ORANGE
    BorderColor<<AzurePrivateLink>> ORANGE
	BorderColor<<AzureExpressRoute>> ORANGE
	BorderColor<<AzureVPNGateway>> ORANGE
    BorderColor<<AzureVirtualMachine>> PURPLE
    BorderColor<<AzureFunction>> PURPLE
    BorderColor<<AzureDataLakeStorage>> CYAN
    BorderColor<<AzureSqlDataWarehouse>> CYAN
    BorderColor<<AzureDataFactory>> CYAN
    BorderColor<<AzureFirewall>> RED
    BorderColor<<AzureNSG>> RED
    BorderColor<<AzureDNS>> CYAN
    BorderColor<<PrivateDnsResolver>> CYAN
}



AzureSubscription(subscriptionIsland, "Business Unit A", null, null, YELLOW) {

    Rectangle "Name Resolution Services" as nameResolution {
        AzureDNS(dnsIslandPrivateZones, "Private DNS Zones", "storage, event hub, AppServices, etc..", "Automated support for Azure servcies with private links", CYAN)
        Rectangle "DNS Private Resolver\ncontoso.com" <<PrivateDnsResolver>> as dnsPrivateResolver
    } 

    together {
        AzureVirtualNetwork(vnetIslandA, "workload a", "AKS, Azure Functions, Virtual Machines", "192.168.0.0/20") #line:red {
        }
        AzureVirtualNetwork(vnetIslandB, "workload b", "Databricks, Synapse", "192.168.16.0/20") #line:red {
        }
    }

    nameResolution -down-> vnetIslandA
    nameResolution -> vnetIslandB
}

AzureSubscription(subscriptionInfrastructure, "Core Infrastructure Services", null, null, YELLOW) {
    AzureVirtualNetwork(vnetBridge, "Bridge - Business Unit A", "Azure Firewall, Bastion, Application Gateway, Private Link Service Endpoints", "10.10.16.0/20") #line:red;line.bold {
    }
    AzureVirtualNetwork(vnetHub, "Hub", "Azure Firewall, DNS servers (contoso.com), Private Link Service Endpoints", "10.10.0.0/20") #line:white
}

AzureSubscription(subscriptionSpoke, "Hybrid Workload", null, null, YELLOW) {
    AzureVirtualNetwork(vnetSpoke, "Spoke", "Custom API: api.contoso.com", "10.10.32.0/20") #line:white

}

vnetIslandA <-[thickness=2,#red]down-> vnetBridge : "Peer"
vnetIslandB <-[thickness=2,#red]down-> vnetBridge : "Peer"
vnetBridge <-down-> vnetHub : "Peer"
vnetHub <-down-> vnetSpoke : "Peer"

@enduml